name: "Test Suite Docker Executor"
description: "Run Containers A and B that create 3 child containers each."

inputs:
  test_suites:
    description: "Comma-separated list of test suites to run"
    required: true

runs:
  using: "docker"
  image: "docker:latest"  # Using the official Docker image
  env:
    DOCKER_HOST: "unix:///var/run/docker.sock"
  entrypoint: "/bin/sh /action/entrypoint.sh"  # Corrected entrypoint as a string
