name: Run Containers A and B

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  run-containers:
    runs-on: ubuntu-latest  # Runs on Ubuntu GitHub runner

    steps:
      # Step 1: Checkout repository to access the code and action files
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx to enable advanced Docker features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Run the custom action
      - name: Run Containers A and B using Docker.sock
        uses: ./action  # Refers to the custom action defined in the action folder
        with:
          test_suites: 'A,B'  # We will create containers for A and B
